### ISSUE TITLE
Safety of character range

### ISSUE THREAD

**Issue by mimi89999** [taylordotfish/base116#1]
Hello,

I noticed that the character range includes non printable characters, that might be difficult to copy or even include in strings in some languages like the range 0x09..0x0b and del at 0x7f.

The range also includes problematic printable chars like double quotes and backslash that will need to be escaped when b116 will be included in a string in source code or in files like JSON.

**Comment by taylordotfish** [comment]
It is true that 0x09 and 0x0a (tab and newline) are not “printable characters” in a strict sense, but they are the two control characters most likely to be preserved in pieces of text, and they commonly occur in text files, unlike more esoteric control characters like vertical tab or form feed.

0x7f is not included in any of the character ranges; `0x20..0x7f` does not include 0x7f. (Similarly, `0x09..0x0b` does not include 0x0b.) But you are right that the ranges do include characters that would be problematic or need escaping in certain applications, in which case Base116 is not a good fit and Base64/Base85/etc. should be used instead.

It is not possible to remove any of the 96 ASCII characters in `[0x09..0x0b, 0x20..0x7f]` from the set that Base116 uses; there would simply not be enough entropy to guarantee one byte per base-116 digit. You would have to change the base to something less than 116, which would be out of scope for this project. You could use a different subset of 96 ASCII characters, but I would argue that all of the ASCII characters not already in use are even less printable.

If I've missed something and there actually is a better set of characters that can still guarantee one byte per base-116 digit, please feel free to open another issue or submit a PR.
